repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0   # Insert the latest tag here
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=1024"]
    -   id: check-ast
        types: [python]
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        types: [yaml]
    -   id: check-json
        types: [json]
    -   id: check-toml
        types: [toml]
    -   id: check-case-conflict
    -   id: check-illegal-windows-names
    -   id: check-symlinks
    -   id: check-xml
        types: [xml]
    -   id: debug-statements
        types: [python]
    -   id: destroyed-symlinks
    -   id: name-tests-test
        args: [--pytest-test-first]
        types: [python]
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, staging]
    -   id: pretty-format-json
        args: [--autofix, --indent, "4", --no-sort-keys]
        types: [json]

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.20
    hooks:
    -   id: uv-lock
    -   id: uv-export

-   repo: https://github.com/astral-sh/ruff-pre-commit
          # Ruff version.
    rev: v0.14.10
    hooks:
          # Run the linter.
    -   id: ruff-check
        args: [--fix]
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        log_file: precommit_logs/pyright.log

    -   id: pytest
        name: pytest
        entry: uv run pytest tests
        language: system
        pass_filenames: false
        types: [python]
        log_file: precommit_logs/pytest.log

ci:
  autofix_prs: true
  autofix_commit_msg: "[pre-commit.ci] Fixing issues with pre-commit"
  autoupdate_schedule: weekly
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit automatically updated revs."
  skip: [pyright, pytest]   # Optionally list ids of hooks to skip on CI
